name: Production Quality Checks

on:
  push:
    branches: [ main, staging ]

jobs:
  # Quality checks for production and staging branches
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Run type checking
      run: npx tsc --noEmit
    
    - name: Run unit tests
      run: npm run test:ci
    
    - name: Build application
      run: npm run build
    
    - name: ✅ Quality checks passed
      run: echo "All quality checks passed. Vercel will handle automatic deployment."
